const A=require('node:assert/strict'),{chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={starts:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(c,n,r){const a=new Float32Array(n);return{length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)}}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){}}}}window.AudioContext=C;window.webkitAudioContext=C};
const cases={
"mirrors":async(p,click,select,check)=>{if(!(await p.evaluate(()=>__flock.state().paused)))await click('pause');const old=await p.evaluate(()=>__flock.state());for(const [id,axis] of [['wind-mirror-horizontal','x'],['wind-mirror-vertical','y']]){await click(id);const s=await p.evaluate(()=>__flock.state());A.equal(s.undoBeats,old.undoBeats+1);for(let i=0;i<80;i++){const a=old.birds[i],b=s.birds[i];A.equal(b.x,a.x);A.equal(b.y,a.y);A.equal(b.vx===0?0:b.vx,axis==='x'?(a.vx===0?0:-a.vx):a.vx);A.equal(b.vy===0?0:b.vy,axis==='y'?(a.vy===0?0:-a.vy):a.vy)}await click('step-back');A.deepEqual(await p.evaluate(()=>__flock.state().birds),old.birds)}},
"editgroups":async(p,click,select,check)=>{await p.locator('#bird-edits>summary').scrollIntoViewIfNeeded();await p.locator('#bird-edits>summary').click();for(const id of ['bird-flight-edits','bird-pair-flight-edits','bird-place-edits']){A.equal(await p.locator('#'+id).evaluate(e=>e.open),false);A.equal(await p.locator('#'+id).evaluate(e=>e.parentElement.closest('details').id),'bird-edits')}A.equal(await p.locator('#bird-left').evaluate(e=>e.closest('details').id),'bird-flight-edits');A.equal(await p.locator('#bird-position-flight-swap').evaluate(e=>e.closest('details').id),'bird-pair-flight-edits');A.equal(await p.locator('#bird-place-left').evaluate(e=>e.closest('details').id),'bird-place-edits');const s=p.locator('#bird-flight-edits>summary');await s.scrollIntoViewIfNeeded();await s.focus();await p.keyboard.press('Enter');A(await p.locator('#bird-left').evaluate(e=>e.checkVisibility()));A.equal(await p.locator('#bird-place-left').evaluate(e=>e.checkVisibility()),false);A.equal(await p.locator('#bird-pair-flight-edits').evaluate(e=>e.open),false);}
};
const messages={"mirrors": "mirroring flight on either axis keeps places and Step back restores every bird", "editgroups": "bird flight and place edits open independently beside their own help"};

(async()=>{A(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});try{for(const width of [390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(e.message));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(120);
const reveal=async l=>{const ids=await l.evaluate(e=>{let a=[];for(let n=e.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS'&&!n.open)a.unshift(n.id);return a});for(const id of ids){A(id);await p.locator('#'+id+'>summary').scrollIntoViewIfNeeded();await p.locator('#'+id+'>summary').click()}};
const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A(await l.isEnabled(),id+' enabled');A(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}),id+' hit');await l.click();await p.waitForTimeout(70)};
const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(70)};
const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(70)};
await cases[mode](p,click,select,check);A.deepEqual(errors,[]);A(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/planner-oct9-${mode}-${width}.png`,fullPage:true});await p.close();}console.log(messages[mode]);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
